---
name: Build Java PR

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@3f1ea88beec7aba96ff7b4f9d4c6edd67d8efff8
    secrets: inherit
