---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: changes
        with:
          list-files: "json"
          filters: |
            json:
              - '**/*.json'

            markdown:
              - '**/*.md'

            renovate-config:
              - 'renovate.json'
              - '.github/renovate.json'
              - 'renovate.json5'
              - '.github/renovate.json5'
              - 'default.json'

            workflow:
              - '.github/workflows/*.yml'
              - '.github/workflows/*.yaml'

            yaml:
              - '**/*.yaml'
              - '**/*.yml'

            dockerfile:
              - '**/*Dockerfile*'
    outputs:
      json: ${{ steps.changes.outputs.json }}
      markdown: ${{ steps.changes.outputs.markdown }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      workflow: ${{ steps.changes.outputs.workflow }}
      yaml: ${{ steps.changes.outputs.yaml }}
      dockerfile_files: ${{ steps.changes.outputs.dockerfile_files }}

  lint-json:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.markdown == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

  lint-renovate:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1

  lint-shell:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0

  lint-workflow:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color

  lint-yaml:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.yaml == 'true'
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .config/yamllint.yml
          strict: true

  lint-docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: ${{ needs.find-changes.outputs.dockerfile_files != '[]' && needs.find-changes.outputs.dockerfile_files != '' }}
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.dockerfile_files) }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ${{ matrix.file }}
