---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_callable.yml@3f1ea88beec7aba96ff7b4f9d4c6edd67d8efff8
    secrets: inherit
